<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Authors>Microlens</Authors>
		<Copyright>Copyright © $([System.DateTime]::Now.Year) Microlens</Copyright>
		<Description>Roslyn-based analyzer and code generator that scaffolds strongly-typed Bogus Faker classes from C# classes and records, with support for enums, collections, dictionaries, and convention-based string values.</Description>
		
		<TargetFramework>netstandard2.0</TargetFramework>
		<OutputType>Library</OutputType>
		<LangVersion>7.3</LangVersion>

		<PackageId>Microlens.Synthesizer.Core</PackageId>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/microlens-solutions/synthesizer</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>bogus;faker;roslyn;scaffolding;boilerplate;semantic-model;code-generation;test-data;</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.20" />
	</ItemGroup>

</Project>
